# -*- coding: utf-8 -*-
"""PyTorchFundamentalsFromScratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usruvp5nMLrxJ5k3ZP9KMvdJxAaeXsSS
"""

import torch
print(torch.__version__)

## Scalar
scalar = torch.tensor(7)
print(scalar)

print(f"The shape of scalar : {scalar.shape}")
print(f"The dimensions of scalar : {scalar.ndim}")

## Getting the python number within a tensor
print(scalar.item())

## Tensor
tensor = torch.tensor([7, 7])
tensor

print(f"The shape of the {tensor} is : {tensor.shape}")
print(f"The dimensions of the {tensor} is : {tensor.ndim}")

## Matrix
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
print(f"The matrix is : {MATRIX}")
print(f"The shape of the matrix is : {MATRIX.shape}")
print(f"The dimensions of the matrix is : {MATRIX.ndim}")

## Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(f"The tensor is : {TENSOR}")
print(f"The shape of the tensor is : {TENSOR.shape}")
print(f"The dimensions of the tensor : {TENSOR.ndim}")

## Creating a random tensor
random_tensor = torch.rand(size = (3, 4))
print(f"The random tensor is : {random_tensor}")
print(f"The type of random tensor is : {random_tensor.dtype}")

## Create random tensor of size (224, 224, 3) , basically height, width and colour channels
random_image_size_tensor = torch.rand(size = (224, 224, 3))
print(f"The random image size tensor is : {random_image_size_tensor}")
print(f"The shape of the tensor is : {random_image_size_tensor.shape}")
print(f"The dimensions of the tensor is : {random_image_size_tensor.ndim}")

## Create a tensor of all zeros
zeros = torch.zeros(size = (2, 3))
print(f"The zeros tensor is : {zeros}")
print(f"The type of the tensor is : {zeros.dtype}")
print(f"The shape of the tensor is : {zeros.shape}")
print(f"The dimensions of the tensor is : {zeros.ndim}")

## Create a tensor of size ones
ones = torch.ones(size = (2, 4))
print(f"The ones tensor is : {ones}")
print(f"The shape of the ones tensor : {ones.shape}")
print(f"The dimensions of the ones tensor : {ones.ndim}")

## Create a range of 0 to 10
zero_to_ten = torch.arange(start = 0, end = 11)
print(f"The tensor range from 0 to 10 is : {zero_to_ten}")

## Tensor of zeros to that of zero_to_ten tensor
ten_zeros = torch.zeros_like(input = zero_to_ten)
print(f"Tensor with 10 zeros is : {ten_zeros}")

## Default datatype for tensors in float32
float32_tensor = torch.tensor([3.0, 4.0, 6.0], dtype = None, device = None, requires_grad = False)
print(f"The tensor is : {float32_tensor}")
print(f"The type of the tensor is : {float32_tensor.dtype}")
print(f"The device of the tensor is : {float32_tensor.device}")
print(f"The shape of the tensor is : {float32_tensor.shape}")

## Create a tensor of values
tensor = torch.tensor([1, 2, 3])
print(f"The tensor is : {tensor}")

## Adding 10 to tensor
print(f"Tensor after adding 10 is : {tensor + 10}")

## Multiply by 10 to tensor
print(f"Tensor after multiplying is : {tensor * 10}")

## Matrix multiplication of tensor
print(f"Two tensors after doing matrix multiplication : {tensor.matmul(tensor)}")

tensor_A = torch.tensor([[1, 2],
                         [4, 5],
                         [7, 8]])
tensor_B = torch.tensor([[4, 5],
                         [6, 7],
                         [9, 10]])
print(f"The shape of tensor A is : {tensor_A.shape}")
print(f"The shape of tensor B is : {tensor_B.shape}")

## Matrix multiplication of two tensors (consider the inner size, must be equal for matrix multiplication)
## We will require to reverse the tensor_B
print(f"Tensor after matrix multiplication is : {tensor_A.matmul(tensor_B.T)}")

## Create a tensor
x = torch.tensor([78, 34, 12, 6, 55, 78, 90, 9])
## Minimum of the tensor
print(f"The minimum of the tensor is : {x.min()}")
## Maximum of the tensor
print(f"The maximum of the tensor is : {x.max()}")
## Mean of the tensor
print(f"The mean of the tensor is : {x.mean(dtype = torch.float32)}")
## Sum of the tensor
print(f"The sum of the tensor is : {x.sum()}")

## Index where the max value lies
print(f"The argmax of the tensor is : {x.argmax()}")
## Index where the min value lies
print(f"The argmin of the tensor is : {x.argmin()}")

## Creating a tensor and changing its datatype
tensor = torch.tensor([2.0, 4.0, 8.0, 9.0, 45.0])
print(f"The tensor is : {tensor}")
print(f"The type of the tensor is : {tensor.dtype}")
float16_tensor = tensor.type(torch.float16)
print(f"The type of the tensor now is : {float16_tensor.dtype}")

## Reshaping the tensor
tensor = torch.arange(1, 11)
print(f"The tensor is : {tensor}")
print(f"The shape of the tensor is : {tensor.shape}")
tensor = tensor.reshape(1, 10)
print(f"The shape of the tensor after reshaping is : {tensor.shape}")

## Changing the view of the tensor
tensor = torch.tensor([2, 3, 4, 5, 6])
print(f"The tensor is : {tensor}")
z = tensor.view(1, 5)
z[0, 1] = 1
print(f"The new tensor is : {z}")
print(f"The old tensor is : {tensor}")

## Stacking tensor
x = torch.tensor([1, 2, 3, 4, 5])
x_stacked = torch.stack([x, x, x, x], dim = 0) ## Stacking horizontally
print(f"Tensor after stacking is : {x_stacked}")

## Stacking vertically
x = torch.tensor([1, 2, 3])
x_stacked = torch.stack([x, x, x], dim = 1)
print(f"Tensor after stacking vertically is : {x_stacked}")

## Remove single dimensions from the tensor
x = torch.rand(size = (1, 3, 1))
print(f"The tensor is : {x}")
print(f"The shape of the tensor is : {x.shape}")
y = x.squeeze()
print(f"Tensor after squeezing : {y}")
print(f"The shape of the tensor after squeezing is : {y.shape}")

## Unsqueeze the tensor
x = torch.rand(size = (2, 3))
print(f"The tensor x is : {x}")
print(f"The shape of the tensor is : {x.shape}")
y = x.unsqueeze(dim = 0)
print(f"The tensor y is : {y}")
print(f"The shape of the tensor y is : {y.shape}")

## Permute the tensor
x = torch.rand(size = (224, 224, 3))
print(f"The shape of the tensor x is : {x.shape}")
y = x.permute(2, 0, 1)
print(f"The shape of the tensor y is : {y.shape}")

## Create a temp tensor
x = torch.tensor([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]])

print(f"The shape of the tensor x is : {x.shape}")

# Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, 0])

# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:,:,1])

import numpy as np

## Convert numpy to tensor
x = np.array([1, 2, 3, 4])
tensor = torch.from_numpy(x)
tensor = tensor.type(torch.float32)
print(f"The tensor is : {tensor}")
print(f"The data tyep of the tensor is : {tensor.dtype}")

## Convert tensor to numpy
numpy_tensor = tensor.numpy()
print(f"The numpy array is : {numpy_tensor}")

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
x = torch.rand(size = (3, 4))
print(f"The tensor is : {x}")
print(f"The tensor shape is : {x.shape}")

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"The current device is : {device}")

